---
http:
- port: 8081
  endpoints:
  - uri: "/get"
    method: "GET"
    status: 200
    body: "OK"
    latency:
      min: 10
      max: 50

  - uri: "/bad"
    method: "GET"
    status: 500
    body: "BAD"
    latency:
      min: 1
      max: 5

---
thrift:
- port: 8082
  endpoints:
  - msg: "echoString"
    body: "gAEAAgAAAAdlY2hvSW50AAAAAAgAAAAAAAEA"
    latency:
      min: 10
      max: 100
